### ISSUE TITLE
wgs実行時にエラー

### ISSUE THREAD

**Issue by ken0-1n** [Genomon-Project/GenomonSummary#1]
実行したコマンド
$ pwd
/home/kchiba/work_summary/GenomonSummary
$ ./genomon_summary wgs sample_german10.csv ~/tmp/summary_test_ori2 genomon.cfg task_param.cfg

ログ
/home/kchiba/tmp/summary_test_ori2/log/coverage_20151125_1101_724858.sh.e5337096

bedtoolsでエラーになっている。-gオプションの引数がないのが原因？
/home/w3varann/tools/bedtools-2.24.0/bin/bedtools shuffle -i /home/kchiba/tmp/summary_test_ori2/summary/German_normal_02/German_normal_02.depth_10000_100.bed -g -incl /home/kchiba/tmp/summary_test_ori2/summary/German_normal_02/German_normal_02.depthgenome.bed -excl /home/kchiba/tmp/summary_test_ori2/summary/German_normal_02/German_normal_02.depth.gap.txt

**Comment by aokad** [comment]
-g オプションをパラメータにし忘れていました。
commitしましたので、ご確認ください。
