### ISSUE TITLE
bamstatsとcoverageの結果をマージする必要がないのではないかと提案する

### ISSUE THREAD

**Issue by ken0-1n** [Genomon-Project/GenomonSummary#2]
この提案は以下の理由による

１．bamstatsはsupplementary alignmentがtotalリード数に含まれないが、coverageには含まれる(coverageにはsamtools depthを使っており、supplementary alignmentリードもdepthに含まれる)。各々のツールで計算のベースとなるリード数が異なっており、そこから計算された各々の結果を1行にまとめるのはよくない。

２．bamstatsはリードグループごとにsummaryを計算しているが、coverageはtotalリードのみで計算している。bamstatsは複数行の結果がでるが、coverageは1行の結果しかでない。それらをマージするのは統一感に欠け、見た目も良くない。

３．結果ファイルのマージではexcel形式での出力をおこなっているため、pythonのexcelモジュールをインストールする必要がある。結果ファイルをマージする必要がなくなれば、モジュールのインストールが２つ減る。

**Comment by aokad** [comment]
totalの1行のみ出力するよう変更しました。
