### ISSUE TITLE
PICARDサマリの3項目の追加を要望

### ISSUE THREAD

**Issue by ken0-1n** [Genomon-Project/GenomonSummary#5]
要望があった3つの項目
PCT_PF_UQ_READS: pcr duplicationを除いたreadの割合
PCT_SELECTED_BASES: SureSelectAllExonV5.bedとその周囲にマップされたbaseの割合
ZERO_CVG_TARGETS_PCT: baitの領域の中で全く読めてない領域の割合

PCT_PF_UQ_READSはGenomonSummaryで同じ意味合いのものが、既に出力されていると記憶しているが、確認する。

**Comment by ken0-1n** [comment]
優先度は高くない

**Comment by aokad** [comment]
PCT_PF_UQ_READSはGenomonSummary (PCAP) で出力している以下2つで同じ意味になるはず。
'#_total_reads' = the total number of reads.
'#_duplicate_reads' = the total number of duplicate reads.
