### ISSUE TITLE
mark duplicateしたリードを含めたすべてのリードのCoverageを算出したい。

### ISSUE THREAD

**Issue by ken0-1n** [Genomon-Project/GenomonSummary#6]
duplicateが除去されていないCoverageを算出してほしいとの要望がありました。

具体的にはsamtools view -F 2048 でフィルタした結果が欲しいです。通常は-F 3072でOKでこの要望が特殊ケースです。そのため実行時のoptionで切り替えができれば良いかなと思います。（柔軟性があるように、samtools view の -F オプションの数値を外部から入力できた方が良いかも。）

優先度は低め、要検討です。

**Comment by aokad** [comment]
v2.0.0にて対応済み
